apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yash-access-role
rules:
- apiGroups: ["subresources.kubevirt.io"]
  resources: ["virtualmachineinstances/console", "virtualmachineinstances/vnc"]
  resourceNames: ["testvm"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jay-deny-role
rules:
- apiGroups: ["subresources.kubevirt.io"]
  resources: ["virtualmachineinstances/console", "virtualmachineinstances/vnc"]
  resourceNames: ["testvm2"]
  verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yash-access-binding
subjects:
- kind: ServiceAccount
  name: rbac-demo-sa  # Replace with the name of the ServiceAccount to be bound for "yash" access
roleRef:
  kind: Role
  name: yash-access-role
  apiGroup: rbac.authorization.k8s.io

