apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-test-2
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "bridge-test-2",
      "type": "bridge",
      "bridge": "br1",
      "ipam": {
        "type": "host-local",
        "subnet": "10.250.251.0/24"
      }
    }'
