apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: ubuntu-vm
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: ubuntu-vm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        resources:
          requests:
            memory: 512M
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: ubuntu
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: ubuntu-vm
            ssh_pwauth: True
            disable_root: false
            ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvMcNd5zd5D3K24L74xM3daYDdIesqZ3IISHxp5Aiefi7+hLg3bOXmJziRCEcL1DhW0LL/3K+wqr4CWgxjlAJGzETqSKflVM6oEswvc78Lx4+NXDvjtsVe/jk+4jfbea+90c1yjoyVwzzVnnHVfRwkM53ThOJKuk/vpdlbkhRsgFl+khvz0sD7Df1UHi8YtDDDvQxxZsUQGcNeeE7QmlhJQsr5BIPnFst5c+TJq0FXk33Tpr3da8bwxKEsTym28d2DglRQz5vi+U/g1FlbCTkNgJcd4HId4r0DJIbxHkrn/LjO0hG9jF7qk0J9xcsujFTItWlPnnhZjKZ3quB3B2HP yash@OPLPT112
        name: cloudinitdisk
