apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-denier-binding
subjects:
- kind: ServiceAccount
  name: rbac-demo-sa
roleRef:
  kind: Role
  name: pod-denier
  apiGroup: rbac.authorization.k8s.io

