apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ubuntu-policy
spec:
  podSelector:
    matchLabels:
      kubevirt.io/domain: testvm3
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.250.250.2/32   # Replace with the IP address you want to deny

