
---
apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name:  ingress-ipblock
  annotations:
    k8s.v1.cni.cncf.io/policy-for: default/bridge-test
spec:
  podSelector:
    matchLabels:
        kubevirt.io/domain: testvm1
  policyTypes:
  - Ingress
  ingress: []

